# --- St. Paul ➝ Minneapolis (I-94 EB direction) ---

# I-94: I-94 EB @ Cretin Ave (Vandalia St)
- camera_id: "C842"
  name: "I-94: I-94 EB @ Cretin Ave (Vandalia St)"
  snapshot_url: "https://video.dot.state.mn.us/video/image/metro/C842"
  corridor: "I-94"
  direction: "EB"
  latitude: 44.95545339085285
  longitude: -93.191995836582

# I-94: I-94 EB @ Franklin Ave
- camera_id: "C839"
  name: "I-94: I-94 EB @ Franklin Ave"
  snapshot_url: "https://video.dot.state.mn.us/video/image/metro/C839"
  corridor: "I-94"
  direction: "EB"
  latitude: 44.964486272
  longitude: -93.216137837

# I-94: I-94 EB E of Franklin Ave
- camera_id: "C30715"
  name: "I-94: I-94 EB E of Franklin Ave"
  snapshot_url: "https://video.dot.state.mn.us/video/image/metro/C30715"
  corridor: "I-94"
  direction: "EB"
  latitude: 44.96266269357945
  longitude: -93.2137705148566

# I-94: I-94 EB @ Riverside Ave
- camera_id: "C837"
  name: "I-94: I-94 EB @ Riverside Ave"
  snapshot_url: "https://video.dot.state.mn.us/video/image/metro/C837"
  corridor: "I-94"
  direction: "EB"
  latitude: 44.964119803881246
  longitude: -93.2300713368883

# I-94: I-94 EB W of Riverside Ave
- camera_id: "C8361"
  name: "I-94: I-94 EB W of Riverside Ave"
  snapshot_url: "https://video.dot.state.mn.us/video/image/metro/C8361"
  corridor: "I-94"
  direction: "EB"
  latitude: 44.96416596916113
  longitude: -93.2338086342616

# I-94: I-94 EB E of Cedar Ave (20th Av)
- camera_id: "C836"
  name: "I-94: I-94 EB E of Cedar Ave (20th Av)"
  snapshot_url: "https://video.dot.state.mn.us/video/image/metro/C836"
  corridor: "I-94"
  direction: "EB"
  latitude: 44.96432896616176
  longitude: -93.2440911877003

# I-94: I-94 EB @ T.H.55
- camera_id: "C8353"
  name: "I-94: I-94 EB @ T.H.55"
  snapshot_url: "https://video.dot.state.mn.us/video/image/metro/C8353"
  corridor: "I-94"
  direction: "EB"
  latitude: 44.96568518791585
  longitude: -93.2533070247372


# --- WB camera ---

# I-94: I-94 WB @ 27th Ave SE
- camera_id: "C8381"
  name: "I-94: I-94 WB @ 27th Ave SE"
  snapshot_url: "https://video.dot.state.mn.us/video/image/metro/C8381"
  corridor: "I-94"
  direction: "WB"
  latitude: 44.96729810745101
  longitude: -93.2201270353046